data_root: /workspace/data           # <- RAW inputs live here
bronze_path: /workspace/lake/bronze  # <- your outputs
silver_path: /workspace/lake/silver
gold_path: /workspace/lake/gold
years: [2024]
services: ["yellow","green"]
dq:
  max_trip_hours: 6
  min_distance_km: 0.1
  min_total_amount: 0
mode: "lambda"   # or "kappa"